// Generated by CoffeeScript 2.3.0
var cush, fs, loadFile, path;

cush = require('cush');

path = require('path');

fs = require('saxon');

loadFile = async function(file, pack) {
  var err, ext, transform;
  // Read the file.
  if (file.content == null) {
    file.content = (await fs.read(pack.resolve(file)));
  }
  try {
    // Transform the file.
    while (true) {
      ({ext} = file);
      if (transform = cush.transformers[ext]) {
        await transform(file, pack);
        if (ext === file.ext) {
          break;
        }
      } else {
        break;
      }
    }
  } catch (error) {
    err = error;
    cush.emit('error', {
      message: 'Failed to transform a file',
      error: err,
      file: pack.resolve(file)
    });
  }
  return file;
};

module.exports = loadFile;
