// Generated by CoffeeScript 2.3.0
var config;

config = {
  exclude: [
    '/.git',
    '/.git/',
    '/node_modules/',
    '.DS_Store', // macOS Finder metadata
    '.*.sw[a-z]',
    '*~', // vim temporary files
    
    // test files
    '__tests__/',
    '__mocks__/',
    'spec/',
    'test/',
    '*.test.*'
  ]
};

module.exports = function(key, val) {
  if (arguments.length === 2) {
    return eval(`config.${key} = val; undefined`);
  } else {
    return eval(`config.${key}`);
  }
};
