// Generated by CoffeeScript 2.3.0
var Emitter, base, cush, log, os, path;

Emitter = require('@cush/events');

path = require('path');

os = require('os');

cush = new Emitter;

// Cache directories
cush.BASE_DIR = path.join(os.homedir(), '.cush');

cush.BUNDLE_DIR = path.join(cush.BASE_DIR, 'bundles');

cush.PACKAGE_DIR = path.join(cush.BASE_DIR, 'packages');

log = require('lodge').debug('cush');

(base = require('elaps')).log || (base.log = log);

// Prevent warnings from going unseen.
cush.on('warning', function(...args) {
  if (cush.listenerCount('warning') === 1) {
    log.warn(...args);
  }
});

cush.on('error', function(...args) {
  if (cush.listenerCount('error') === 1) {
    log.error(...args);
  }
});

module.exports = cush;
