// Generated by CoffeeScript 2.3.0
var assign, cush, def;

cush = require('cush');

def = function(key, value) {
  return Object.defineProperty(cush, key, {value});
};


// Parsers

cush.parsers = {
  '.css': require('./parse/css'),
  '.js': require('./parse/js')
};

def('_parseImports', function(file) {
  var parse;
  if (parse = cush.parsers[file.ext]) {
    return parse.imports(file.content);
  } else {
    return [];
  }
});


// Transformers

assign = function(a, b) {
  var k;
  for (k in b) {
    a[k] = b[k];
  }
  return a;
};

cush.transformers = [require('./transform/coffee'), require('./transform/sucrase')].reduce(assign, {});
