// Generated by CoffeeScript 2.3.1
var ErrorTracer, portal;

({portal} = require('@cush/sorcery'));

ErrorTracer = function(sources, options) {
  var trace;
  trace = portal(sources, options);
  return function(err, source) {
    var traced;
    if (err.column == null) {
      err.column = err.col || 0;
      delete err.col;
    }
    if (err.filename == null) {
      err.filename = err.file;
      delete err.file;
    }
    if (!(traced = trace(err.line, err.column - 1))) {
      err.filename = source || null;
      return;
    }
    err.line = traced.line;
    err.column = traced.column;
    err.filename = traced.source;
  };
};

module.exports = ErrorTracer;
