// Generated by CoffeeScript 2.3.1
var Module, evalFile, fs, loaders, path;

Module = require('module');

path = require('path');

fs = require('saxon/sync');

evalFile = function(file, ext) {
  var load;
  if (!(load = loaders[ext || path.extname(file)])) {
    throw Error(`Cannot eval '${file}' without a loader`);
  }
  if (fs.isFile(file)) {
    return load(file);
  } else {
    return null;
  }
};

loaders = {
  '': fs.read,
  '.js': function(file) {
    delete Module._cache[file];
    return Module._load(file);
  },
  '.json': function(file) {
    return JSON.parse(fs.read(file));
  }
};

module.exports = evalFile;
