// Generated by CoffeeScript 2.3.1
var extRegex, knownExts;

knownExts = require('@cush/known-exts');

extRegex = function(...exts) {
  exts = knownExts.concat(...exts);
  exts = Array.from(new Set(exts)).sort().map(function(ext) {
    return ext.slice(1);
  });
  exts = exts.join('|').replace(/\./g, '\\.');
  return new RegExp(`\\.(${exts})$`);
};

module.exports = extRegex;
