// Generated by CoffeeScript 2.3.1
var base, findPackage, fs, os, path;

path = require('path');

fs = require('saxon/sync');

os = require('os');

base = /^[.\/]$/;

findPackage = function(file) {
  var dir;
  dir = path.dirname(file);
  while (true) {
    if (fs.isFile(path.join(dir, 'package.json'))) {
      return dir;
    }
    if (base.test(dir = path.dirname(dir))) {
      break;
    }
  }
  return null;
};

module.exports = findPackage;
