// Generated by CoffeeScript 2.3.0
var getCallSite, returnCallSites;

returnCallSites = function(e, stack) {
  return stack;
};

getCallSite = function(offset = 0) {
  var callsite, orig;
  orig = Error.prepareStackTrace;
  Error.prepareStackTrace = returnCallSites;
  callsite = Error().stack[1 + offset];
  Error.prepareStackTrace = orig;
  return callsite;
};

module.exports = getCallSite;
