// Generated by CoffeeScript 2.3.0
var Module, getModule, path;

Module = require('module');

path = require('path');

getModule = function(filename) {
  var mod;
  if (!(mod = Module._cache[filename])) {
    mod = new Module('', null);
    mod.filename = filename;
    mod.paths = Module._nodeModulePaths(path.dirname(filename));
    mod.loaded = true;
  }
  return mod;
};

module.exports = getModule;
