// Generated by CoffeeScript 2.3.1
var defaults;

defaults = [
  '/.git',
  '/.git/',
  '/node_modules/',
  '.DS_Store', // macOS Finder metadata
  '.*.sw[a-z]',
  '*~', // vim temporary files
  
  // test files
  '__tests__/',
  '__mocks__/',
  'spec/',
  'test/',
  '*.test.*'
];

module.exports = function(globs) {
  return defaults.concat(globs || []);
};
