// Generated by CoffeeScript 2.3.1
var mapSources, sorcery;

sorcery = require('@cush/sorcery');

// Update the sourcemap of a file.
mapSources = function(source, result) {
  source.map = source.map ? sorcery([result, source], {
    includeContent: false
  }) : result.map;
  source.content = result.content;
};

module.exports = mapSources;
