// Generated by CoffeeScript 2.3.1
var isObject, merge, push;

push = Function.apply.bind([].push);

isObject = function(val) {
  return (val != null) && val.constructor === Object;
};

merge = function(a, b) {
  var key, val;
  if (Array.isArray(b)) {
    push(a, b);
    return a;
  }
  for (key in b) {
    val = b[key];
    if (Array.isArray(val)) {
      if (Array.isArray(a[key])) {
        push(a[key], val);
        continue;
      }
    } else if (isObject(val)) {
      if (isObject(a[key])) {
        u.merge(a[key], val);
        continue;
      }
    }
    if (val !== void 0) {
      a[key] = val;
    }
  }
  return a;
};

module.exports = merge;
