// Generated by CoffeeScript 2.3.1
var crypto, sha256;

crypto = require('crypto');

sha256 = function(data, len) {
  var hash;
  hash = crypto.createHash('sha256').update(data).digest('hex');
  if (typeof len === 'number') {
    return hash.slice(0, len);
  } else {
    return hash;
  }
};

module.exports = sha256;
