// Generated by CoffeeScript 2.3.0
var cush, uhoh;

cush = require('../index');

uhoh = function(err) {
  if (err.constructor === Object) {
    err = Object.assign(new Error(err.message), err);
  } else {
    err = new Error(err);
  }
  Error.captureStackTrace(err, uhoh);
  cush.emit('error', err);
  throw err;
};

module.exports = uhoh;
