// Generated by CoffeeScript 2.3.1
var uhoh;

uhoh = function(error, code) {
  if (error.constructor === Object) {
    error = Object.assign(new Error(error.message), error);
  } else {
    error = new Error(error);
    if (code != null) {
      error.code = code;
    }
  }
  Error.captureStackTrace(error, uhoh);
  throw error;
};

module.exports = uhoh;
